Repository emulsify-ds/emulsify-ui-kit, pull requests merged in 2024-08, with the labels that each got.

#128 EMULSIF-230: Convert accordion to support SDC
  src/components/accordion/accordion.component.yml
  src/components/accordion/accordion.stories.js
  src/components/accordion/accordion.yml
  src/components/tokens/_tokens.scss
Labels: 🎉 Passes Functional Review, 🎉 Passes Code Review

#130 EMULSIF-232: Convert Blockquote to support SDC
  src/components/blockquote/blockquote.component.yml
  src/components/blockquote/blockquote.stories.js
  src/components/blockquote/blockquote.yml
  src/components/tokens/_tokens.scss
Labels: 🎉 Passes Functional Review, 🎉 Passes Code Review

#131 EMULSIF-233: Convert Button to support SDC
  src/components/button/button.component.yml
  src/components/button/button.stories.js
  src/components/tokens/_tokens.scss
Labels: 🎉 Passes Functional Review, 🎉 Passes Code Review

#132 EMULSIF-234: Convert card to support sdc
  src/components/card/card-horizontal.yml
  src/components/card/card.component.yml
  src/components/card/card.yml
  src/components/card/cards.stories.js
  src/components/tokens/_tokens.scss
Labels: 🎉 Passes Functional Review, 👉 Needs Work

#134 EMULSIF-235: Convert forms to support SDC
  src/components/forms/checkbox/checkbox.yml
  src/components/forms/forms.component.yml
  src/components/forms/forms.stories.js
  src/components/forms/radio/radio.yml
  src/components/forms/select/_select.scss
  src/components/forms/select/select.yml
  src/components/tokens/_tokens.scss
Labels: 🎉 Passes Functional Review, 🎉 Passes Code Review

#135 EMULSIF-237: Convert Links to support SDC
  src/components/links/link/link.component.yml
  src/components/links/link/link.yml
  src/components/links/link/links.stories.js
  src/components/tokens/_tokens.scss
Labels: 🎉 Passes Functional Review, 👉 Needs Work

#136 EMULSIF-238: Convert lists to support SDC
  src/components/lists/list.component.yml
  src/components/lists/list.stories.js
  src/components/lists/list.twig
  src/components/lists/list.yml
  src/components/tokens/_tokens.scss
Labels: 🎉 Passes Functional Review, 🎉 Passes Code Review

#123 🔵 Western University of Pennsylvania Blue
  src/components/accordion/_accordion.scss
  src/components/docs/examples/_basic.scss
  src/components/docs/examples/_home.scss
  src/components/docs/examples/_program.scss
  src/components/docs/examples/assets/_header.twig
  src/components/docs/examples/basic.stories.js
  src/components/docs/examples/basic.twig
  src/components/docs/examples/basic.yml
  src/components/docs/examples/home.stories.js
  src/components/docs/examples/home.twig
  src/components/docs/examples/program.stories.js
  src/components/docs/examples/program.twig
  src/components/docs/examples/program.yml
  src/components/forms/select/_select.scss
  src/components/menus/main-menu/_02-main-menu-link.scss
  src/components/storybook-styles/storybook.scss
  src/components/text/text/_body.scss
  src/components/text/text/_text.scss
  src/components/tokens/_tokens.scss
  src/components/tokens/border-radius-tokens/border-radius-tokens.twig
  src/components/tokens/border-tokens/border-tokens.twig
  src/components/tokens/breakpoint-tokens/breakpoint-tokens.twig
  src/components/tokens/color-tokens/color-tokens.twig
  src/components/tokens/fontSize-tokens/font-sizes.stories.js
  src/components/tokens/line-height/line-height.stories.js
  src/components/tokens/line-height/line-height.twig
  src/components/tokens/opacity-tokens/opacity-tokens.twig
  src/components/tokens/size-tokens/size-tokens.twig
  src/components/tokens/spacing-tokens/spacing-tokens.twig
  src/components/tokens/type-scale/type-scale.stories.js
  src/components/tokens/type-scale/type-scale.twig
  src/images/example/basic-camera-image.png
  src/style.scss
  src/stylesheets/mixins.scss
  src/tokens/figma.tokens.json
  src/tokens/transformed.tokens.json
Labels: 🎉 Passes Functional Review, 🎉 Passes Code Review, 🎉 Ready to Merge

#138 Fix accordion missing styles
  src/components/accordion/_accordion.scss
  src/components/tokens/_tokens.scss
Labels: 🎉 Passes Functional Review, 🎉 Passes Code Review, 🎉 Ready to Merge

#139 Design tokens for the Announcement component
  src/components/tokens/_tokens.scss
  src/tokens/figma.tokens.json
  src/tokens/transformed.tokens.json
Labels: 👍 Ready for Review

#129 EMULSIF-231: Convert Audio player to support SDC
  src/components/audio-player/audio-player.component.yml
  src/components/audio-player/audio-player.stories.js
  src/components/audio-player/audio-player.yml
  src/components/tokens/_tokens.scss
Labels: 🎉 Passes Functional Review, 🎉 Passes Code Review, 🎉 Ready to Merge

#137 EMULSIF-240: Convert Menus to support sdc
  src/components/menus/breadcrumbs/breadcrumbs.component.yml
  src/components/menus/breadcrumbs/breadcrumbs.yml
  src/components/menus/inline/inline-menu.component.yml
  src/components/menus/inline/inline-menu.yml
  src/components/menus/main-menu/main-menu.component.yml
  src/components/menus/main-menu/main-menu.yml
  src/components/menus/menus.stories.js
  src/components/menus/social-menu/social-menu.component.yml
  src/components/menus/social-menu/social-menu.yml
  src/components/tokens/_tokens.scss
Labels: 🎉 Passes Functional Review, 🎉 Passes Code Review, 🎉 Ready to Merge

#143 Design tokens for Banner component
  src/components/tokens/_tokens.scss
  src/tokens/figma.tokens.json
  src/tokens/transformed.tokens.json
Labels: 🎉 Passes Functional Review, 🎉 Passes Code Review, 🎉 Ready to Merge

#147 Design tokens for Header component
  src/components/tokens/_tokens.scss
  src/tokens/figma.tokens.json
  src/tokens/transformed.tokens.json
Labels: 🎉 Passes Functional Review, 🎉 Passes Code Review, 🎉 Ready to Merge

#146 Design tokens for Footer component
  src/components/tokens/_tokens.scss
  src/tokens/figma.tokens.json
  src/tokens/transformed.tokens.json
Labels: 🎉 Passes Functional Review, 🎉 Passes Code Review, 🎉 Ready to Merge

#141 EMULSIF-241: Convert Pager to support SDC
  src/components/pager/pager-both-ellipses.component.yml
  src/components/pager/pager-both-ellipses.yml
  src/components/pager/pager-first-last.component.yml
  src/components/pager/pager-first-last.yml
  src/components/pager/pager-next-ellipses.component.yml
  src/components/pager/pager-next-ellipses.yml
  src/components/pager/pager-prev-ellipses.component.yml
  src/components/pager/pager-prev-ellipses.yml
  src/components/pager/pager.component.yml
  src/components/pager/pager.stories.js
  src/components/pager/pager.yml
  src/tokens/tokens.scss
Labels: 🎉 Passes Code Review

#142 EMULSIF-242: Convert Status to support SDC
  src/components/status/status.component.yml
  src/components/status/status.stories.js
  src/components/status/status.yml
Labels: 🎉 Passes Code Review

#144 EMULSIF-243: Convert Tables to support SDC
  src/components/tables/tables.component.yml
  src/components/tables/tables.stories.js
  src/components/tables/tables.yml
Labels: 🎉 Passes Code Review

#145 EMULSIF-244: Convert Tabs to support SDC
  src/components/tabs/tabs.component.yml
  src/components/tabs/tabs.stories.js
  src/components/tabs/tabs.yml
Labels: 🎉 Passes Code Review

#148 EMULSIF-245: Convert Text to support SDC
  src/components/text/headings/headings.component.yml
  src/components/text/headings/headings.yml
  src/components/text/text.stories.js
  src/components/text/text/blockquote.component.yml
  src/components/text/text/blockquote.yml
  src/components/text/text/code.component.yml
  src/components/text/text/code.yml
Labels: 🎉 Passes Code Review

#149 EMULSIF-246: Convert Videos to support SDC
  src/components/videos/video-embed.component.yml
  src/components/videos/video-embed.yml
  src/components/videos/video-html5.component.yml
  src/components/videos/video-html5.yml
  src/components/videos/videos.stories.js
Labels: 🎉 Passes Code Review
